CREATE TABLE "users" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_name" TEXT,
	"address" TEXT,
	"email" TEXT,
	"payment_info" TEXT,
	PRIMARY KEY("id")
);




CREATE TABLE "products" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"product_name" TEXT,
	"category" INTEGER,
	"rating" DECIMAL,
	"description" TEXT,
	"price" MONEY,
	"pic" VECTOR,
	"quantity" INTEGER,
	"nsn" INTEGER,
	"manufacturer" TEXT,
	PRIMARY KEY("id")
);




CREATE TABLE "role" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"role_name" TEXT,
	"description" TEXT,
	"category_list" INTEGER,
	PRIMARY KEY("id")
);




CREATE TABLE "category" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"category_name" TEXT,
	"description" TEXT,
	PRIMARY KEY("id")
);




CREATE TABLE "manufacturer" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"mnf_name" TEXT,
	PRIMARY KEY("id")
);




CREATE TABLE "orders" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user" INTEGER,
	"price" MONEY,
	"date" DATE,
	"status" INTEGER,
	"items_ordered" INTEGER,
	PRIMARY KEY("id")
);




CREATE TABLE "status" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"status" TEXT,
	PRIMARY KEY("id")
);



ALTER TABLE "category"
ADD FOREIGN KEY("id") REFERENCES "products"("category")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "manufacturer"
ADD FOREIGN KEY("mnf_name") REFERENCES "products"("manufacturer")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "role"
ADD FOREIGN KEY("category_list") REFERENCES "category"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "status"
ADD FOREIGN KEY("id") REFERENCES "orders"("status")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "users"
ADD FOREIGN KEY("id") REFERENCES "orders"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "products"
ADD FOREIGN KEY("id") REFERENCES "orders"("items_ordered")
ON UPDATE NO ACTION ON DELETE NO ACTION;